resources:
  repositories:
  - repository: MyGitHubRepo # The name used to reference this repository in the checkout step
    type: github
    endpoint: MyGitHubServiceConnection

pool:
#  vmImage: ubuntu-latest
  name: devopspool-wb
  
steps:
- checkout: self
- checkout: https://github.com/vbalbarin/avd.git 
- script: |
    cd $(Agent.BuildDirectory)/avd
    git remote add github https://github.com/vbalbarin/avd.git
  displayName: 'Add GitHub as a remote'
 