# resources:
#   repositories:
#   - repository: avd # The name used to reference this repository in the checkout step
#     type: github
#     endpoint: avd-terraform


pool:
  name: devopspool-wb

steps:
- checkout: git://avd-terraform/avd-terraform
  persistCredentials: true
- bash: |
    git remote add github https://github.com/vbalbarin/avd.git
    git fetch github
    git pull github main
    git config user.email "avd-terraform@wirebyte.us"
    git config user.name "avd-terraform"
    git commit -m "Mirror from GitHub"
    git push origin
    az repos pr create --source-branch main --target-branch customer-main
  displayName: "Mirror GH to Az Devops"

#env:
#  AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)