---
# file: azure-pipelines.yml

jobs:
- template: templates/mirror_ghb_ado.yml
  parameters:
    pool_name: $(MANAGED_DEVPOOL) # set MANAGED_DEVPOOL='' to use msft runner
    ado_tgt_reponame: $(ADO_TARGET_REPO) 
    ghb_src_reponame: $(GHB_SOURCE_REPO)
    email: $(USER_EMAIL)
    username: $(USER_NAME)
