# resources:
#   repositories:
#   - repository: avd # The name used to reference this repository in the checkout step
#     type: github
#     endpoint: avd-terraform


pool:
  name: $(MANAGED_DEVPOOL)

# the following is not complete
steps:
- template: templates/mirror_ghb_ado.yml
  parameters: 
    ado_tgt_reponame: $(ADO_TARGET_REPO) 
    ghb_src_reponame: $(GHB_SOURCE_REPO)
    email: $(USER_EMAIL)
    username: $(USER_NAME)
