resources:
  repositories:
  - repository: avd # The name used to reference this repository in the checkout step
    type: github
    endpoint: avd-terraform
    name: vbalbarin/avd

pool:
#  vmImage: ubuntu-latest
  name: devopspool-wb
  
steps:
- checkout: self
- checkout: avd
- script: |
    cd $(Agent.BuildDirectory)/avd
    git remote add github https://github.com/vbalbarin/avd.git
  displayName: 'Add GitHub as a remote'
 