pool:
#  vmImage: ubuntu-latest
  name: devopspool-wb

trigger: none

steps:
- checkout: avd-terraform
  persistCredentials: true
- bash: |
    git remote add github https://github.com/vbalbarin/avd.git
    git fetch github
    git pull github
    git config user.email "avd-terraform@wirebyte.us"
    git config user.name "avd-terraform"
    git commit -m "Mirror from GitHub"
    git push origin
    az repos pr create --source-branch main --target-branch customer-main
  name: 'Mirror GH to Az Devops'

env:
  AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)