pool:
#  vmImage: ubuntu-latest
  name: devopspool-wb
  
steps:
- script: |
    git clone https://avd-wb@dev.azure.com/avd-wb/avd-terraform/_git/avd-terraform ../MirrorFromGitHub
    cd ../MirrorFromGitHub
    git remote add github https://github.com/vbalbarin/avd.git
  displayName: 'Add GitHub as a remote'
 